config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :articles
  resources :coaches
  resources :pages
  resources :users
  resources :calendar
 
  get 'info/about'

  get 'info/privacy'

  get 'info/license'

  root 'welcome#index'

end

app/models/coach.rb
class Coach < ApplicationRecord
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:name, :user_id, :email, :address, :coach_type)
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_for(coach) do |f| %>
  <% if coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :coach_type %>
    <%= f.text_field :coach_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Email</th>
      <th>Address</th>
      <th>Coach type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td><%= coach.user_id %></td>
        <td><%= coach.email %></td>
        <td><%= coach.address %></td>
        <td><%= coach.coach_type %></td>
        <td><%= link_to 'Show', coach %></td>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coach', new_coach_path %>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coach.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @coach.user_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @coach.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @coach.address %>
</p>

<p>
  <strong>Coach type:</strong>
  <%= @coach.coach_type %>
</p>

<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>